install.packages("readxl")
install.packages("matrixStats")
library(matrixStats)
library("readxl")
library(reshape2)
library(readxl)
library(plyr)
library(tibble)

workingdic <- getwd()
workingdic <- trimws(workingdic)  # Trimming and spaces at either ends
print(workingdic)
setwd(workingdic)


economy_CBIC <- read_xlsx("InputFiles/Irish Industries in Ireland.xlsx", sheet = "Expenditure into Irish Economy")  #irish companies 
economy_CBFC <- read_xlsx("InputFiles/Foreign Industries in Ireland.xlsx", sheet = "Expenditure into Irish Economy")
economy_column_name <- c("Indutry", "Industry_type", "Value_in",  "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009",
                       "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017")
colnames(economy_CBIC) <- economy_column_name
colnames(economy_CBFC) <- economy_column_name
 
head(economy_CBIC)
head(economy_CBFC)


##############################################  Total economy contribution of each Irish and Foreign owned industry ###############################################################

Irish_Owned <- colSums(Filter(is.numeric, economy_CBIC))
Foreign_Owned <- colSums(Filter(is.numeric, economy_CBFC))

data <- data.frame(Irish_Owned, Foreign_Owned)
head(data)
max_value <- max(max(data$Irish_Owned), max(data$Foreign_Owned))
max_value

data
barplot(t(data),beside=T,ylim=c(0,(max_value+10000)), main = "Economy contribution of Irish and Foreign companies each year", xlab="Year",ylab="Expenditure towards Irish Economy", col = rainbow(2),axis.lty="solid")
color.names = c("Red","Blue")
legend("top", rownames(t(data)),cex =0.7,fill=color.names,title="Irish/Foreign companies")


############################################## Which industry has given max business in year 2016 for Foreign industries #############################################

economy_CBFC$Index <- 1:nrow(economy_CBFC)

max_value <- max(economy_CBFC$`2016`)

barplot(economy_CBFC$`2016`,ylim=c(0,(max_value+10000)), xlab = "Industry", ylab = "Millions of Euros", main = "Contribution to Economy in millions of Euros for 2016" ,names.arg =  Sales$Index)
legend("top",paste(economy_CBFC$Index ," " , economy_CBFC$Indutry) , cex = 0.5, title = "Index to Industry")

######################################### Total economy generated by Irish and Foreign Owned companies each year by Industry Type  #################################################################


economy_irish_company <- aggregate(Filter(is.numeric, economy_CBIC), by=list(economy_CBIC$Industry_type), FUN=sum)
economy_foreign_company <- aggregate(Filter(is.numeric, economy_CBFC), by=list(economy_CBIC$Industry_type), FUN=sum)

Energy_irish <- colSums(Filter(is.numeric, economy_irish_company[c("1"),]))
Information_irish <- colSums(Filter(is.numeric, economy_irish_company[c("2"),]))
Manufacturing_irish <- colSums(Filter(is.numeric, economy_irish_company[c("3"),]))

Energy_foreign <- colSums(Filter(is.numeric, economy_foreign_company[c("1"),]))
Information_foreign <- colSums(Filter(is.numeric, economy_foreign_company[c("2"),]))
Manufacturing_foreign <- colSums(Filter(is.numeric, economy_foreign_company[c("3"),]))

par(mfrow = c(2,2))

plotlinegraph <- function(data1, data2, data_msg)
{
  min_value <- min(min(data1), min(data2))
  max_value <- max(max(data1), max(data2))
  
  plot(data1, type = "o", ylim = c(min_value, max_value),col="red", xlab = "Years", ylab = "economy in Millions of Euros", main = data_msg, xaxt = 'n')
  axis(side=1,at=c(1,5,10,15,20),labels=c("2000","2005","2010","2015", "2020"))
  lines(data2, type = "o", col = "blue")
  legend("topleft", legend=c("Irish", "Foreign"), col=c("red", "blue"), lty=1:2, cex=0.5)

}

plotlinegraph(Energy_irish, Energy_foreign, "Economy contribution from Energy sector")
plotlinegraph(Information_irish, Information_foreign, "Economy contribution from Information sector")
plotlinegraph(Manufacturing_irish, Manufacturing_foreign, "Economy contribution from Manufacturing sector")

