install.packages("readxl")
install.packages("matrixStats")
library(matrixStats)
library("readxl")
library(reshape2)
library(ggplot2)

workingdic <- getwd()
workingdic <- trimws(workingdic)  # Trimming and spaces at either ends
print(workingdic)
setwd(workingdic)

employment_irish <- read_xlsx("InputFiles/Irish Industries in Ireland.xlsx", sheet = "Employment")  #irish companies 
employment_foreign <- read_xlsx("InputFiles/Foreign Industries in Ireland.xlsx", sheet = "Employment")
empl_column_names <- c("Indutry", "Industry_type", "Value_in",  "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009",
                         "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017")
colnames(employment_irish) <- empl_column_names
colnames(employment_foreign) <- empl_column_names

head(employment_irish)
head(employment_foreign)


################################### Over-All Employment Generated by industries in Ireland over the years ################################################

Irish_Owned <- colSums(Filter(is.numeric, employment_irish))
Foreign_Owned <- colSums(Filter(is.numeric, employment_foreign))

data <- data.frame(Irish_Owned, Foreign_Owned)

max_value <- max(data$Irish_Owned + data$Foreign_Owned)
max_value

data

barplot(t(data), col= rainbow(2), besides = FALSE,
           ylim=c(0,(max_value+12000)),ylab = "Employment number", xlab="Years",
           main="Employment numbers by Irish and Foreign companies")

legend("top",rownames(t(data)),cex =0.6,fill=color.names,title="Irish/Foreign companies")

########################################## Top 5 companies to generate Total employment generated from 2000-2017 #########################################################

employment_irish$total_employment_generated <- rowSums(Filter(is.numeric, employment_irish))
employment_irish <-employment_irish[order(-employment_irish$total_employment_generated),]
employment_irish <- employment_irish[1:5,]

employment_foreign$total_employment_generated <- rowSums(Filter(is.numeric, employment_foreign))
employment_foreign <-employment_foreign[order(-employment_foreign$total_employment_generated),]
employment_foreign <- employment_foreign[1:5,]

employment_irish$total_employment_generated
employment_foreign$total_employment_generated

par(mfrow = c(1,2))
pie(employment_irish$total_employment_generated, labels = employment_irish$total_employment_generated, 
    main = "Top 5 employent by irish industries from 2000-2017", col = rainbow(5))
legend("topleft", c(employment_irish$Indutry), cex = 0.5,fill = rainbow(5))

pie(employment_foreign$total_employment_generated, labels = employment_foreign$total_employment_generated, 
    main = "Top 5 employent by irish industries from 2000-2017", col = rainbow(5))
legend("topright", c(employment_foreign$Indutry), cex = 0.5,fill = rainbow(5))


